#!/bin/bash

# do not use 'set -e'. It will abort a whole build if, i.e. the
# memory of a single 4MB-Device exceeds.
# set -e

# get some build-config
source buildconfig.conf

RELEASES="
    https://downloads.openwrt.org/releases/19.07.5/targets/
    https://downloads.openwrt.org/releases/19.07.6/targets/
    https://downloads.openwrt.org/snapshots/targets/"

# General variables
FALTER_REPO_BASE="src/gz openwrt_falter https://firmware.berlin.freifunk.net/feed/"
FREIFUNK_RELEASE=""


##################
#   CMD-PARSER   #
##################

# POSIX-compliant getopt(s)-free old-style-supporting option parser from phk@[se.unix]
# https://stackoverflow.com/a/33191693
print_usage() {
  echo "Usage:

  $0 {p|v|t|s|p|d} [ARG...]

Options:

  -p|--packageset [PATH]
    give a path to the packageset

  -v|--version [VERSION]
    OpenWrt-release to be used. i.e. '19.07'

  -t|--target [TARGET]
    target like 'ath79'

  -s|--sub-target [SUBTARGET]
    something like 'generic'. This is optional.

  -r|--router [ROUTER-PROFILE]
    give a router-profile like 'glinet_gl-ar150'. This is optional.

  -d|--development
    use development-feeds instead of release-feeds

" >&2
}

if [ $# -le 0 ]; then
  print_usage
  exit 1
fi

opt=
while :; do

  if [ $# -le 0 ]; then
    # no parameters remaining -> end option parsing
    break
  elif [ ! "$opt" ]; then
    # we are at the beginning of a fresh block
    # remove optional leading hyphen and strip trailing whitespaces
    opt=$(echo "$1" | sed 's/^-\?\([a-zA-Z0-9\?-]*\)/\1/')
  fi

  # get the first character -> check whether long option
  first_chr=$(echo "$opt" | awk '{print substr($1, 1, 1)}')
  [ "$first_chr" = - ] && long_option=T || long_option=F

  # note to write the options here with a leading hyphen less
  # also do not forget to end short options with a star
  case $opt in
    -)
      # end of options
      shift
      break
      ;;

    d*|-development)
      echo "using dev-feeds."
      FALTER_REPO_BASE="$FALTER_REPO_BASE""new/"
      ;;

    p*|-packageset)
      if [ "$2" ]; then
        echo "Packagset is: $2"
        PARSER_PACKAGESET="$2"
        shift
      else
        echo "Packageset parameters incomplete!" >&2
        print_usage
        exit 1
      fi
      ;;

    v*|-version)
      if [ "$2" ]; then
        echo "OpenWrt-version is: $2"
        PARSER_OWT="$2"
        shift
      else
        echo "Version parameters incomplete!" >&2
        print_usage
        exit 1
      fi
      ;;

    t*|-target)
    if [ "$2" ]; then
      echo "Target is: $2"
      PARSER_TARGET="$2"
      shift
    else
      echo "Target parameters incomplete!" >&2
      print_usage
      exit 1
    fi
    ;;

    s*|-sub-target)
    if [ "$2" ]; then
      echo "Sub-Target is: $2"
      PARSER_SUBTARGET="$2"
      shift
    else
      echo "Sub-Target parameters incomplete!" >&2
      print_usage
      exit 1
    fi
    ;;

    r*|-router)
    if [ "$2" ]; then
      echo "Router is: $2"
      PARSER_PROFILE="$2"
      shift
    else
      echo "router-profile parameters incomplete!" >&2
      print_usage
      exit 1
    fi
    ;;

    h*|\?*|-help)
      print_usage
      exit 0
      ;;

    *)

      if [ "$long_option" = T ]; then
        opt=$(echo "$opt" | awk '{print substr($1, 2)}')
      else
        opt=$first_chr
      fi
      printf 'Error: Unknown option: "%s"\n' "$opt" >&2
      print_usage
      exit 1
      ;;

  esac

  if [ "$long_option" = T ]; then
    # if we had a long option then we are going to get a new block next
    shift
    opt=

  else
    # if we had a short option then just move to the next character
    opt=$(echo "$opt" | awk '{print substr($1, 2)}')

    # if block is now empty then shift to the next one
    [ "$opt" ] || shift
  fi
done


# specify feed based on openwrt-version
if [[ "$PARSER_OWT" =~ 19.07 ]]; then # regex-matching. Not portable to sh!
  FALTER_REPO_BASE="$FALTER_REPO_BASE""openwrt-19.07/"
else
  FALTER_REPO_BASE="$FALTER_REPO_BASE""master/"
fi



#################
#   FUNCTIONS   #
#################

function read_packageset {
	local PACKAGE_SET_PATH=$1
	# read packageset, while removing comments, empty lines and newlines
	PACKAGE_SET=$(cat $PACKAGE_SET_PATH | sed -e '/^#/d; /^[[:space:]]*$/d' | tr '\n' ' ')
}

function fetch_subdirs {
    URL=$1
    curl -s $URL | grep href | grep -v 'snapshots\|releases' | awk -F'"' '{print $4}'
}

function is_wave1_device {
	# detect, if a device has wave1-chipset by its firmware
	local profile=$1
	DEVICE_PACKAGES=$(make info | grep "$profile:" -A 2 | tail -n1 | cut -d':' -f2)
          if [[ "$DEVICE_PACKAGES" =~ ath10k-firmware-qca988x || "$DEVICE_PACKAGES" =~ ath10k-firmware-qca9887 ]]; then
            subsitute_ct_driver "$DEVICE_PACKAGES"
          fi
}

function subsitute_ct_driver {
	# generate a packagelist with ct-drivers/firmware substituted by normal one
        local DEVICE_PACKAGES="$@"
        echo "wave1 chipset detected..."
        echo "change firmware and drivers in packagelist to non-ct counterparts..."
        PACKAGE_SET_DEVICE=$(echo "$PACKAGE_SET"" $DEVICE_PACKAGES" | sed -e 's/ath10k-firmware-qca988x-ct/ath10k-firmware-qca988x -ath10k-firmware-qca988x-ct/g; s/ath10k-firmware-qca9887-ct/ath10k-firmware-qca9887 -ath10k-firmware-qca9887-ct/g; s/kmod-ath10k-ct/kmod-ath10k -kmod-ath10k-ct/g')
}

function derive_branch_from_url {
    URL=$1
    RELEASE_TYPE=$(echo $URL | awk -F'/' '{print $4}')
    case $RELEASE_TYPE in
      releases)
        echo $URL | awk -F'/' '{print $5}' | cut -d. -f1-2
      ;;
      snapshots)
        echo snapshot
      ;;
    esac
}

function generate_embedded_files {
    FALTERBRANCH="$1"
    # call scripts to generate dynamic data in embedded files
    local TARGET=$(echo $IMAGE_BUILDER_URL | cut -d'/' -f 7)
    local SUBTARGET=$(echo $IMAGE_BUILDER_URL | cut -d'/' -f 8)

    # Get the FREIFUNK_RELEASE variable from the falter/packages repo
    # located in the falter-common package.
    [ "snapshot" == $FALTERBRANCH ] && FALTERBRANCH="master"
    [ $FALTERBRANCH != "master" ] && FALTERBRANCH="openwrt-$FALTERBRANCH"
    local TMP=$(curl -q https://raw.githubusercontent.com/Freifunk-Spalter/packages/$FALTERBRANCH/packages/falter-common/files-common/etc/freifunk_release)
    eval $TMP

    ../../scripts/01-generate_banner.sh $FREIFUNK_RELEASE $NICKNAME $TARGET $SUBTARGET
    ../../scripts/03-luci-footer.sh $FREIFUNK_RELEASE $NICKNAME $TARGET $SUBTARGET $FREIFUNK_OPENWRT_BASE
    export REPO # export repo line to inject into images. contains whitespace...
    ../../scripts/04-include-falter-feed.sh
}

function start_build {
    IMAGE_BUILDER_URL=$1
    local TMP=$2 # slice packageset-name from path
    local PKG_SET=$(echo $TMP | rev | cut -d'/' -f1 | rev | cut -d'.' -f1)
    local DEVICE=$3
    FILENAME=$(basename $IMAGE_BUILDER_URL)
    FOLDERNAME=$(basename $FILENAME .tar.xz)
    BRANCH=$(derive_branch_from_url $IMAGE_BUILDER_URL)
    echo "building using: $IMAGE_BUILDER_URL"
    echo "selected branch: $BRANCH"

    # store imagebuilders in cache. Reload, if there is a newer version avaiable
    local CACHE="../imagebuilder_cache"
    if [ ! -d $CACHE ]; then mkdir -p $CACHE; fi
    cd $CACHE
    wget -N --no-if-modified-since $IMAGE_BUILDER_URL
    cd ../build
    # pull imagebuilder from cache-dir
    cp ../imagebuilder_cache/$FILENAME $FILENAME

    echo $PWD

    rm -rf $FOLDERNAME
    tar -xJf $FILENAME

    cd $FOLDERNAME
    # patch json-info, so that it will contain every image, not just the last one
    cp -f ../../patches/json_overview_image_info.py scripts/json_overview_image_info.py

    case $BRANCH in
      snapshot)
        ispos=7
	;;
      *)
        ispos=8
	;;
    esac

    INSTR_SET=$(grep "openwrt_base" repositories.conf | awk -F'/' "{print \$$ispos}")
    echo "selected instruction set: $INSTR_SET"

    REPO="$FALTER_REPO_BASE/packages/$INSTR_SET/falter"
    echo "injecting repo line: $REPO"
    echo "$REPO" >> repositories.conf

    # the hexadecimal number represents the fringerprint of the key. Refer to third section of https://openwrt.org/docs/guide-user/security/keygen#generate_usign_key_pair
    local URL="http://buildbot.berlin.freifunk.net/buildbot/feed/packagefeed_master.pub"
    echo "loading package-feed key from $URL"
    curl "$URL" > keys/61a078a38408e710

    generate_embedded_files $BRANCH
    if [ -z $DEVICE ]; then
      for profile in $(make info | grep ":$" | cut -d: -f1 | grep -v "Available Profiles" | grep -v "Default"); do
          echo "start building $profile..."

          is_wave1_device $profile
          if [ -z $PACKAGE_SET_DEVICE ]; then
              PACKAGE_SET_DEVICE="$PACKAGE_SET"
          fi

          make image PROFILE="$profile" PACKAGES="$PACKAGE_SET_DEVICE" FILES="../../embedded-files/" EXTRA_IMAGE_NAME="freifunk-falter-${FREIFUNK_RELEASE}"
          PACKAGE_SET_DEVICE="" # empty packageset for use with next wave1-device
          echo "finished"
      done
    else
      echo "start building $DEVICE..."

      is_wave1_device $DEVICE
      if [ -z $PACKAGE_SET_DEVICE ]; then
          PACKAGE_SET_DEVICE="$PACKAGE_SET"
      fi

      make image PROFILE="$DEVICE" PACKAGES="$PACKAGE_SET_DEVICE" FILES="../../embedded-files/" EXTRA_IMAGE_NAME="freifunk-falter-${FREIFUNK_RELEASE}"
      PACKAGE_SET_DEVICE=""
    fi
    # move binaries into central firmware-dir, sort them for packagesets, there was given one.
    if [ $PKG_SET ]; then
		rsync -a --remove-source-files bin/targets/* ../../firmwares/$PKG_SET/
    else
		rsync -a --remove-source-files bin/targets/* ../../firmwares/
    fi

    cd ..
}


##############
#    MAIN    #
##############

if [ "$PARSER_PACKAGESET" == "all" ]; then
	# build all imageflavours. For this, get paths of packagesets
	# fetch paths of packagelists (depends on openwrt-version). If not unique, chose most recent version of possibilities.
	PSET_PATHS=$(find packageset | sort | grep -e "/$PARSER_OWT" | grep .txt | tail -n3)
	echo $PSET_PATHS
	#exit
else
	read_packageset "$PARSER_PACKAGESET"
fi

# remove artifacts of last build
mkdir -p firmwares
rm -rf firmwares/*
mkdir -p build
rm -rf build/*
cd build


# read command-line parameters
CONF_RELEASE="$PARSER_OWT"
CONF_TARGET="$PARSER_TARGET"
CONF_SUBTARGET="$PARSER_SUBTARGET"
CONF_DEVICE="$PARSER_PROFILE"



if [ -z "$CONF_RELEASE" ] && [ -z "$CONF_TARGET" ]; then
	# build all targets for all releases
	for release in $RELEASES; do
	    for target in $(fetch_subdirs $release); do
	        for subtarget in $(fetch_subdirs $release$target); do
		    imagebuilder=$(fetch_subdirs $release$target$subtarget | grep imagebuilder)
		    start_build $release$target$subtarget$imagebuilder
	        done
	    done
	done
	exit
elif [ -z "$CONF_TARGET" ]; then
	# build one release for all targets
	# fetch release-link. in case there is more than one, fetch recent release.
	RELEASE_LINK=$(echo "$RELEASES" | tr ' ' '\n' | grep "$CONF_RELEASE" | tail -n 1)
	for target in $(fetch_subdirs "$RELEASE_LINK"); do
		for subtarget in $(fetch_subdirs $RELEASE_LINK$target); do
			imagebuilder=$(fetch_subdirs $RELEASE_LINK$target$subtarget | grep imagebuilder)
		    start_build $RELEASE_LINK$target$subtarget$imagebuilder
	    done
	done
	exit
else
	# there was given a release and a target
	RELEASE_LINK=$(echo "$RELEASES" | tr ' ' '\n' | grep "$CONF_RELEASE" | tail -n 1)
	# if there was defined a subtarget and option device, only build that.
	if [ -n "$CONF_SUBTARGET" ]; then
		# build directly that subtarget. if requested, for all image types.
		TARGET_LIST="$RELEASE_LINK$CONF_TARGET/$CONF_SUBTARGET/"
		IMAGEBUILDER=$(fetch_subdirs "$TARGET_LIST" | grep imagebuilder)
		if [ "$PSET_PATHS" ]; then
			for PKG_SET in $PSET_PATHS; do
				echo "BUILDING 3 PACKAGELISTS"
				read_packageset "../$PKG_SET"
				start_build "$TARGET_LIST$IMAGEBUILDER" $PKG_SET $CONF_DEVICE
			done
		else
			echo "BUILDING 1 PACKAGLIST"
			start_build "$TARGET_LIST$IMAGEBUILDER" targets $CONF_DEVICE
		fi
		exit
	fi
	# otherwise, fetch all subtargets and build them one after another.
		for subtarget in $(fetch_subdirs "$RELEASE_LINK$CONF_TARGET/"); do
			imagebuilder=$(fetch_subdirs "$RELEASE_LINK$CONF_TARGET/$subtarget" | grep imagebuilder)
			if [ "$PSET_PATHS" ]; then
				for PKG_SET in $PSET_PATHS; do
					echo "BUILDING 3 PACKAGELISTS"
					read_packageset "../$PKG_SET"
					start_build "$RELEASE_LINK$CONF_TARGET/$subtarget$imagebuilder" $PKG_SET
				done
		    else
				echo "BUILDING 1 PACKAGLIST"
				start_build "$RELEASE_LINK$CONF_TARGET/$subtarget$imagebuilder"
		    fi
	    done
	exit
fi
