---
name: lint

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

on: [push, pull_request]

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Lint
        run: |
          sudo apt update
          sudo apt install -y  shellcheck
          make lint
